name: build

on: 
  push:
    paths:
      - 'src/**'

jobs:
  update-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create .gitguard Directory and Copy Contents
      run: |
        mkdir -p .gitguard
        cp -r src/* .gitguard/

    - name: Zip .gitguard Directory
      run: |
        mkdir -p dist
        zip -r dist/gitguard.zip .gitguard

    - name: Configure Git
      run: |
        git config --global user.email "segin.bytes@gmail.com"
        git config --global user.name "segin-GH"

    - name: Commit and Push Changes
      run: |
        git add dist/gitguard.zip
        git commit -m "ci: automated update for dist"
        git push
      env:
        GIT_AUTH_TOKEN: ${{ secrets.GIT_GUARD_TOKEN }}
